### ISSUE TITLE
Infix to Postfix Expression Using Stack

### ISSUE THREAD

**Issue by 7sakshi7** [Developer-Student-Clubs-MMDU/Data-Structures-and-Algorithms#5]

**Comment by codemii** [comment]
Hi @7sakshi7 , could you please assign this to me. Thanks!!

**Comment by tanisha12j** [comment]
Hi, i am Tanisha bansal.I m interested in contributing in this issue.

**Comment by 7sakshi7** [comment]
this is assigned to @tanisha12j
