### ISSUE TITLE
Implement Queue Using One Stack

### ISSUE THREAD

**Issue by 7sakshi7** [Developer-Student-Clubs-MMDU/Data-Structures-and-Algorithms#8]

**Comment by codemii** [comment]
Hi @7sakshi7 , could you please assign this to me. Thanks!!

**Comment by 7sakshi7** [comment]
yes sure

**Comment by codemii** [comment]
Thanks @7sakshi7 , will raise PR today.

**Comment by codemii** [comment]
Hi @7sakshi7 , raise below PR for this issue. Please review and approve this. Thanks!!
https://github.com/Developer-Student-Clubs-MMDU/Data-Structures-and-Algorithms/pull/29

**Comment by codemii** [comment]
Hi @7sakshi7 , could you please add hacktoberfest-accepted label to it?
