### ISSUE TITLE
Print Range of Number (like: 1 2 3 4 ...n ) without using a number in program(code)

### ISSUE THREAD

**Issue by raj4477** [Developer-Student-Clubs-MMDU/Data-Structures-and-Algorithms#9]
Input Format: Contain a single line of an integer N
Output : 1 2 3 4 5 ..N
Disclaimer: You cannot use numbers in programs like 
`int i = 1;`
you can not use 1 in the code.

**Comment by Nikhila-KS** [comment]
Hi, my name is Nikhila
am interested in contributing in this issue

**Comment by m0hit-kumar** [comment]
> Hi, my name is Nikhila am interested in contributing in this issue

ok sure, i am assigning this to u
